name: 'Vansah-testing Integration'
description: 'GitHub action to import test results into "Vansah" - A complete Test Management tool for Jira.'
author: 'Testpoint'
inputs:
  path:
    required: true
    description: 'Just give me the file'
outputs:
  name:
    description: 'The count of imported files.'
runs:
  using: 'node16'
  main: 'index.js'
